const routes = module.exports = require('next-routes')()

routes
    .add('home')
    .add('about')
    .add('login')
    .add('signUp')
    .add('contact')
    .add('new-project')
    .add('profile')
    .add('faq')
    .add('why')
    .add('/profile/edit', 'edit')
    .add('/:id', 'project')
    .add('/:id/edit', 'edit-project')