// Toggle action
export const TOGGLE_SIGN_IN_MODAL = 'TOGGLE_SIGN_IN_MODAL';
export const TOGGLE_SIGN_UP_MODAL = 'TOGGLE_SIGN_UP_MODAL';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_SIDEBAR_POSITION = 'TOGGLE_SIDEBAR_POSITION';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const NEXT_STEP = 'NEXT_STEP'
export const PREVIOUS_STEP = 'PREVIOUS_STEP'

export const LOG_OUT = 'LOG_OUT'